config/routes.rb
RailsSite::Application.routes.draw do
  resources :pages
  resources :users

  resources :sessions do
    collection do
      post 'newaccount'
      get 'signup'
    end
  end

  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/logout' => 'sessions#destroy'
  match '/auth/status' => 'sessions#me'
  match '/auth/newaccount' => 'sessions#newaccount'

  match '/:id' => 'pages#show'

  root :controller => 'pages', :action => 'index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    user ||= User.new

    if user.in_role? 'officer'
      can :manage, :all
    else
      can :read, :all
      cannot :read, [User]
    end
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash[:provider], hash[:uid])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authentication.create(:user => user, :uid => hash[:uid], :provider => hash[:provider])
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  def to_param
    slug
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  has_and_belongs_to_many :roles
  
  def self.create_from_hash!(hash)
    create(:realname => hash[:realname], :email => hash[:email])
  end

  def in_role?(rolename)
    self.roles.find_by_name(rolename.to_s) != nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Sorry! You don't appear to have permissions to do that!"
    redirect_to root_url
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end

  def require_login!
    # TODO: Make this go to a page with login options.
    # TODO: session[:return_to] or similar, to get back to this page.
    if !current_user
      flash[:error] = 'You must be logged in to access this page.'
      redirect_to '/'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  load_resource :find_by => :slug
  authorize_resource

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find_by_slug(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])
    @page.edited_by = session[:user_id]

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, :notice => 'Page was successfully created.' }
        format.json { render :json => @page, :status => :created, :location => @page }
      else
        format.html { render :action => "new" }
        format.json { render :json => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find_by_slug(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, :notice => 'Page was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find_by_slug(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    omniauth = request.env['omniauth.auth']
    if omniauth
      # Register
      @auth_info = { :provider => params[:provider] }
      @auth_info[:realname] = omniauth['user_info']['name'] ? omniauth['user_info']['name'] : ''
      @auth_info[:email] = omniauth['user_info']['email'] ? omniauth['user_info']['email'] : ''
      @auth_info[:uid] = omniauth['uid'] ? omniauth['uid'] : ''
      case params[:provider]
      when 'some_special_case'
        # Handle any special cases here.
      end
      # render :text => @auth_info.to_yaml and return
      session[:auth_info] = @auth_info

      if @auth = Authentication.find_from_hash(@auth_info)
        # Log in
        self.current_user = @auth.user
        session[:user_id] = @auth.user.id
        redirect_to(request.env['omniauth.origin'] || '/') and return
      else
        render signup_sessions_path and return
      end

    else
      flash[:error] = 'An error has occurred and has been logged.'
      redirect_to root_url
    end
  end

  def newaccount
    auth = session[:auth_info]
    if params[:commit] == 'Cancel'
      session[:auth_info] = nil
      redirect_to root_url and return
    end
    @auth = Authentication.create_from_hash(auth, current_user)
    session[:user_id] = @auth.user.id
    flash[:success] = 'Hey! You have made a new account! Thanks!'
    redirect_to root_url and return
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url and return
  end

  def me
    render :text => "Session: #{session[:user_id]}" and return
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    syntax_highlighter(Redcarpet.new(text, *options).to_html).html_safe
  end
  
  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <title>The University of Akron Amateur Radio Club, W8UPD</title>

    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-22277117-1']);
      _gaq.push(['_trackPageview']);
      
      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
   
  </head>
  <body>
    <div id="global">
      <div id="header">
        <div class="constrain cf">
          <%= link_to 'W8UPD', '/', :class => 'clubcall fl' %>
          <span class="fr">
            <form id="search">
              <input class="search_text" type="text" value="Search W8UPD..." x-webkit-speech />
            </form>
          </span>
        </div>
      </div>
      <div id="linkbar">
        <div class="constrain linkbar_bg cf">
          <ul id="linkbarlist">
 
            <li><a href="/repeater/">Repeater</a></li>
            <li><a href="/calendar/">Calendar</a></li>
		        <li><a href="/projects/">Projects</a></li>
		        <li><a href="/net/">Nets</a></li>
		        <li><a href="/links/">Links</a></li>
		        <li><a href="/irc/">IRC Chat</a>
		        <li><a href="/newsletters/">News Letters</a></li>
		        <li><a href="http://group.w8upd.org/">Email List</a></li>
            <li><a href="http://oldsite.w8upd.org/">Old Site</a></li>
          </ul>
          <% if current_user %>
            <ul id="linkbarlistright">
              <li><%= link_to 'Profile', '/me' %></li>
              <li><%= link_to 'Log out', '/auth/logout' %></li>
            </ul>
          <% else %>
            <ul id="linkbarlistright">
              <li><%= link_to 'Log in', '#', :id => 'loginlink' %></li>
            </ul>
          <% end %>
        </div>
      </div>
      
      <div id="loginbar" class="cf">
        <div class="constrain">
          <span style="line-height: 35px; vertical-align: middle;">Log in using: </span>
          <%= link_to image_tag('authbuttons/png/facebook_32.png'), '/auth/facebook' %>
        </div>
      </div>
      
      <div id="content" class="cf">
        <% flash.each do |key, msg| %>
          <%= content_tag :div, msg, :id => key, :class => 'cf' %>
        <% end %>
      
        <%= yield %>
      </div>
      <div id="footer">
        <span class="fl">Powered by Ruby on Rails<br /></span>
        <span class="fr">&copy; 2011-present The University of Akron Amateur Radio Club</span>
      </div>
    </div>
    <script type="text/javascript">
      $(document).ready(function() {
        $('#loginbar').hide();
        $('#loginlink').click(function() {
          $('#loginbar').slideToggle('fast');
          return false;
        });
      });
    </script>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Title: <%= f.text_field :title %><br />
  Slug/URL: <%= f.text_field :slug %><br />
  Content: <%= f.text_area :content %><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.slug %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p><%= markdown @page.content %></p>

<% if can? :manage, @page %>
  <%= link_to 'Edit', edit_page_path(@page) %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <%= f.label :realname, 'Name' %>
      <%= f.text_field :realname %>
    </p>
    
    <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :roles %>
      <% Role.find(:all).each do |role| %>
        <div>
          <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
          <%= role.name %>
        </div>
      <% end %>
    </p>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.realname %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<p>
  <b>name:</b>
  <%= @user.realname %>
</p>

<p>
  <b>email:</b>
  <%= @user.email %>
</p>

<p>
  <b>roles:</b>
  <%= @user.roles.map {|role| role.name}.join ', ' %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>